name: CI
on: [pull_request, workflow_call, workflow_dispatch]
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - run: cargo fmt --check

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - run: cargo check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - run: cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        id: rust-cache
      - name: Check for cache hit
        run: echo "cache-hit=${{ steps.rust-cache.outputs.cache-hit }}"
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - run: cargo nextest run --all-features
